local function readFile(path)
    local file = assert(io.open(path, "rb"))
    local source = file:read("*a")
    file:close()
    return source
end

local main = readFile("main.lua")
local store = readFile("ServerStore.lua")
local client = readFile("SyncClient.lua")
local api = readFile("api.json")

local function contains(source, text, message)
    assert(source:find(text, 1, true), message or ("missing expected annotation integration: " .. text))
end

contains(api, '"get_annotations"', "annotation delta GET route missing")
contains(api, '"put_annotations"', "annotation batch PUT route missing")
contains(api, '"path": "/api/v1/annotations"', "annotation API must target Stage 7 endpoint")
contains(api, '"required_params": ["document", "legacy_device_id", "annotations"]', "annotation writes must include physical document and device identity")
contains(client, 'function SyncClient:getAnnotations(username, userkey, document, after, limit, callback)', "annotation GET helper missing")
contains(client, 'self:_async("get_annotations", username, userkey', "annotation GET must use authenticated async transport")
contains(client, 'function SyncClient:putAnnotations(username, userkey, payload, callback)', "annotation PUT helper missing")
contains(client, 'self:_async("put_annotations", username, userkey, payload, callback)', "annotation PUT must use authenticated async transport")

contains(store, 'annotation_sync = {}', "persistent per-server annotation state missing")
contains(store, 'annotations = nil', "server capability cache must include annotations")
contains(store, 'annotations_version = nil', "server capability cache must include annotation protocol version")
contains(store, 'function ServerStore:getAnnotationState(server_id, document)', "annotation cursor/revision state getter missing")
contains(store, 'function ServerStore:saveAnnotationState(server_id, document, state)', "annotation cursor/revision state persistence missing")
contains(store, 'self.data.annotation_sync[id] = nil', "removing a server must remove its annotation state")

contains(main, 'AnnotationAdapter = require("AnnotationAdapter")', "KOReader annotation adapter must be loaded")
contains(main, 'function ProgressSyncDeluxe:serverSupportsAnnotations(server)', "annotation sync must be capability gated")
contains(main, 'capabilities.annotations == true', "annotation sync must require explicit server support")
contains(main, 'tonumber(capabilities.annotations_version)', "annotation sync must honor protocol version")
contains(main, 'self.ui.annotation.annotations', "live KOReader annotation collection must be used")
contains(main, 'self.ui.doc_settings:saveSetting("annotations", annotations)', "synced annotations must persist in book settings")
contains(main, 'Event:new("AnnotationsModified")', "KOReader must be notified after remote annotation mutation")
contains(main, 'function ProgressSyncDeluxe:syncAnnotationsForServer(server, document, callback)', "annotation convergence loop missing")
contains(main, 'AnnotationAdapter.collectLocalChanges(', "local edits/deletes must be captured")
contains(main, 'local pending_by_id = {}', "local dirty annotation ids must be protected during delta pull")
contains(main, 'not pending_by_id[tostring(remote.id)]', "remote deltas must not silently rebase pending local writes")
contains(main, 'AnnotationAdapter.applyRemote(annotations, remote)', "remote accepted/conflict copies must apply to KOReader")
contains(main, 'AnnotationAdapter.remember(state, remote, annotations)', "server revision must be remembered after accepted/conflict writes")
contains(main, 'client:getAnnotations(server.username, server.userkey, document, after, 200', "annotation deltas must be paged")
contains(main, 'math.min(#pending, offset + 199)', "annotation writes must be chunked")
contains(main, 'client:putAnnotations(server.username, server.userkey', "local annotation changes must be uploaded")
contains(main, 'self:syncAnnotationsForServer(server, document)', "successful progress pushes must trigger annotation convergence")
contains(main, 'self:syncAnnotationsForServer(server, annotation_document)', "progress pulls must trigger annotation convergence")
contains(main, 'self.store:setCapability(server.id, "annotations", annotation_supported)', "capability probe must cache annotation support")
contains(main, 'self.store:setCapability(server.id, "annotations_version", annotation_version)', "capability probe must cache annotation version")
contains(main, 'annotations = true', "Deluxe device capability payload must advertise annotation support")
contains(main, '_("Annotations")', "server UI must expose annotation support")

local collect_position = assert(main:find("AnnotationAdapter.collectLocalChanges(", 1, true))
local get_position = assert(main:find("client:getAnnotations(server.username, server.userkey, document, after, 200", 1, true))
assert(collect_position < get_position, "local dirty state must be captured before remote deltas are pulled")

local put_start = assert(main:find("client:putAnnotations(server.username, server.userkey", 1, true))
local put_end = assert(main:find("local pullDeltas", put_start, true))
local put_block = main:sub(put_start, put_end - 1)
assert(not put_block:find("state.cursor =", 1, true), "PUT response must not advance the per-document delta cursor")

print("annotation_sync_test.lua: OK")
