local function readFile(path)
    local file = assert(io.open(path, "rb"))
    local source = file:read("*a")
    file:close()
    return source
end

local main = readFile("main.lua")
local lifecycle = readFile("ProgressLifecycleController.lua")
local store = readFile("ServerStore.lua")
local adapter = readFile("DeluxeProfileAdapter.lua")
local vocabulary_sync = readFile("VocabularySync.lua")
local statistics_sync = readFile("ReadingStatisticsSync.lua")
local annotation_sync = readFile("AnnotationSync.lua")
local settings_sync = readFile("SettingsBackupSync.lua")
local profile_backup_sync = readFile("DeluxeProfileBackupSync.lua")
local menu = readFile("PluginMenuController.lua")

local function contains(source, text, message)
    assert(source:find(text, 1, true), message or ("missing data-sharing privacy contract: " .. text))
end

contains(store, "ServerStore.DATA_SHARING_VERSION = 2", "Vocabulary consent must advance the data-sharing schema so existing users review the new categories")
contains(store, 'for _, field in ipairs({ "annotations_enabled", "reading_statistics_enabled", "settings_backup_enabled", "deluxe_config_backup_enabled", "vocabulary_enabled", "vocabulary_context_enabled" }) do', "legacy enhanced-data categories must migrate to explicit safe defaults")
contains(store, "server[field] = false", "legacy enhanced-data sharing must default off")
contains(store, "function ServerStore:getServersNeedingDataSharingReview()", "legacy servers must remain discoverable for one-time review")
contains(store, "server.annotations_enabled = server.annotations_enabled == true", "annotation consent must persist as an explicit boolean")
contains(store, "server.reading_statistics_enabled = server.reading_statistics_enabled == true", "statistics consent must persist as an explicit boolean")
contains(store, "server.settings_backup_enabled = server.settings_backup_enabled == true", "settings-backup consent must persist as an explicit boolean")
contains(store, "server.deluxe_config_backup_enabled = server.deluxe_config_backup_enabled == true", "config-backup consent must persist as an explicit boolean")
contains(store, "server.vocabulary_enabled = server.vocabulary_enabled == true", "Vocabulary Builder consent must persist as an explicit boolean")
contains(store, "server.vocabulary_context_enabled = server.vocabulary_enabled and server.vocabulary_context_enabled == true or false", "reading-context consent must fail closed when Vocabulary Builder is disabled")
contains(store, "function ServerStore:getVocabularyState(server_id)", "per-server Vocabulary delta state must be persisted separately")

contains(main, 'title = T(_("Data shared with %1"), serverLabel(server))', "data-sharing choices must identify which server they apply to")
contains(main, '_("Reading Progress: On (required)")', "reading progress must remain visibly always on")
contains(main, 'label = _("Book Metadata")', "existing metadata choice must remain visible")
contains(main, 'label = _("Annotations / Highlights / Notes")', "annotation sharing choice missing")
contains(main, 'label = _("Reading Statistics")', "statistics sharing choice missing")
contains(main, 'label = _("KOReader Settings Backup")', "KOReader settings backup choice missing")
contains(main, 'label = _("Deluxe-Sync Config Backup")', "protected config backup choice missing")
contains(main, 'label = _("Vocabulary Builder")', "Vocabulary Builder sharing choice missing")
contains(main, 'label = _("Vocabulary Reading Context")', "Vocabulary reading-context sharing choice missing")
contains(main, 'includes your configured server URLs, usernames, and saved authentication keys', "protected config backup must warn about credential scope")
contains(main, 'Vocabulary Reading Context can include surrounding book passages and highlighted text', "reading-context consent must warn that book excerpts can leave the reader")
contains(main, 'local button = dialog:getButtonById(item.id)', "data-sharing toggles must use ButtonDialog's public button lookup API")
contains(main, 'local context_button = dialog:getButtonById("vocabulary_context_sharing")', "Vocabulary parent toggle must update the context button through ButtonDialog")
assert(not main:find("dialog.button_table:getButtonById", 1, true), "ButtonDialog does not expose button_table; using it crashes toggle callbacks")
contains(main, 'Enable Vocabulary Builder before sharing reading context.', "reading context must not be independently enabled without Vocabulary Builder")
contains(main, "server.data_sharing_version = ServerStore.DATA_SHARING_VERSION", "saving data-sharing choices must acknowledge the current consent schema")
contains(main, 'title = T(_("Review data sharing (%1 remaining)"), #pending)', "review flow must show how many configured servers still need consent")
contains(main, 'message = T(_("Saved for %1. Servers remaining to review: %2."), serverLabel(updated), #remaining)', "review flow must explicitly confirm a per-server save before advancing")
contains(main, 'message = T(_("Saved for %1. Data-sharing review is complete."), serverLabel(updated))', "review flow must confirm when all server reviews are complete")
contains(main, "self.store:getServersNeedingDataSharingReview()", "review flow must use the versioned migration marker")
contains(lifecycle, "UIManager:scheduleIn(0.5, function() owner:showDataSharingReview() end)", "reader startup must schedule data-sharing review")
contains(main, 'data_sharing_version = ServerStore.DATA_SHARING_VERSION,', "new or explicitly saved full-page server settings must use the current consent schema while untouched legacy servers stay reviewable")
contains(main, 'metadata_enabled = server.metadata_enabled ~= false', "existing metadata default/choice behavior must stay intact")
contains(main, 'EnhancedDataSyncCoordinator = require("EnhancedDataSyncCoordinator")', "optional enhanced data must use the coordinator")
assert(not menu:find('text = _("Sync optional data now")', 1, true), "manual optional-data convergence is redundant with normal progress push and should not clutter the menu")
assert(not menu:find('owner:nudgeOptionalDataAll(true)', 1, true), "menu must not trigger a redundant global optional-data convergence pass")
contains(main, 'self:nudgeOptionalData(server, payload.document, false)', "successful progress push/retry paths must still nudge optional-data convergence per server")
contains(main, "function ProgressSyncDeluxe:onCloseDocument()", "close-document compatibility hook missing")
contains(main, "self.progress_lifecycle_controller:onCloseDocument()", "close-document hook must delegate to the lifecycle controller")
local close_start = assert(lifecycle:find("function ProgressLifecycleController:onCloseDocument()", 1, true), "close-document lifecycle implementation missing")
local close_end = assert(lifecycle:find("\nend\n", close_start, true), "close-document lifecycle implementation is malformed")
local close_body = lifecycle:sub(close_start, close_end)
contains(close_body, "self:autoSyncPush()", "close-document must preserve the normal progress push")
assert(not close_body:find("nudgeOptionalDataAll", 1, true), "close-document must not trigger a redundant global optional-data convergence pass")

contains(annotation_sync, "server.annotations_enabled ~= true", "annotations must fail closed without consent")
contains(statistics_sync, "server.reading_statistics_enabled ~= true", "statistics must fail closed without consent")
contains(settings_sync, "server.settings_backup_enabled ~= true", "KOReader settings backup must fail closed without consent")
contains(profile_backup_sync, "server.deluxe_config_backup_enabled ~= true", "Deluxe-Sync config backup must fail closed without consent")
contains(vocabulary_sync, "server.vocabulary_enabled ~= true", "Vocabulary Builder must fail closed without consent")
local vocabulary_gate = assert(vocabulary_sync:find("server.vocabulary_enabled ~= true", 1, true), "Vocabulary consent gate missing")
local vocabulary_read = assert(vocabulary_sync:find("VocabularyAdapter.scan(include_context)", 1, true), "Vocabulary DB read missing")
assert(vocabulary_gate < vocabulary_read, "Vocabulary consent must be checked before the local database is read")
contains(vocabulary_sync, 'local include_context = server.vocabulary_context_enabled == true and capabilities.vocabulary_context == true', "reading context must require both local consent and server capability")

contains(adapter, "server.data_sharing_version = existing and", "profile restore must keep consent local to the receiving reader")
contains(adapter, "server.annotations_enabled = existing and existing.annotations_enabled == true or false", "profile restore must not import annotation consent")
contains(adapter, "server.reading_statistics_enabled = existing and existing.reading_statistics_enabled == true or false", "profile restore must not import statistics consent")
contains(adapter, "server.settings_backup_enabled = existing and existing.settings_backup_enabled == true or false", "profile restore must not import settings-backup consent")
contains(adapter, "server.deluxe_config_backup_enabled = existing and existing.deluxe_config_backup_enabled == true or false", "profile restore must not import protected config-backup consent")
contains(adapter, "server.vocabulary_enabled = existing and existing.vocabulary_enabled == true or false", "profile restore must not import Vocabulary Builder consent")
contains(adapter, "server.vocabulary_context_enabled = server.vocabulary_enabled and existing and existing.vocabulary_context_enabled == true or false", "profile restore must not import Vocabulary reading-context consent or leave it enabled without Vocabulary Builder")

print("data_sharing_privacy_test.lua: OK")
