local function readFile(path)
    local file = assert(io.open(path, "rb"))
    local source = file:read("*a")
    file:close()
    source = source:gsub("\r\n", "\n"):gsub("\r", "\n")
    return source
end

local main = readFile("main.lua")
local controller = readFile("EnhancedDataSyncController.lua")
local restore = readFile("RestoreMigrationController.lua")
local store = readFile("ServerStore.lua")
local client = readFile("SyncClient.lua")
local api = readFile("api.json")
local adapter = readFile("DeluxeProfileAdapter.lua")
local settings_sync = readFile("SettingsBackupSync.lua")
local profile_backup_sync = readFile("DeluxeProfileBackupSync.lua")

local function contains(source, text, message)
    assert(source:find(text, 1, true), message or ("missing Deluxe profile integration: " .. text))
end

local function excludes(source, text, message)
    assert(not source:find(text, 1, true), message or ("unexpected Deluxe profile integration: " .. text))
end

contains(api, '"put_deluxe_profile"', "Deluxe profile upload API method missing")
contains(api, '"get_deluxe_profile_candidate"', "Deluxe profile candidate API method missing")
contains(api, '"request_deluxe_profile_restore"', "Deluxe profile restore-request API method missing")
contains(api, '"get_current_deluxe_profile_restore"', "pending Deluxe profile restore API method missing")
contains(api, '"complete_deluxe_profile_restore"', "Deluxe profile restore acknowledgement API method missing")

contains(client, 'function SyncClient:putDeluxeProfile(username, userkey, payload, callback)', "protected-profile upload SyncClient helper missing")
contains(client, 'function SyncClient:getDeluxeProfileCandidate(username, userkey, legacy_device_id, koreader_device_id, callback)', "candidate SyncClient helper missing")
contains(client, 'function SyncClient:requestDeluxeProfileRestore(username, userkey, profile_id, legacy_device_id, koreader_device_id, callback)', "restore-request SyncClient helper missing")
contains(client, 'function SyncClient:getCurrentDeluxeProfileRestore(username, userkey, legacy_device_id, koreader_device_id, callback)', "pending restore SyncClient helper missing")
contains(client, 'function SyncClient:completeDeluxeProfileRestore(username, userkey, request_id, payload, callback)', "restore acknowledgement SyncClient helper missing")

contains(store, 'deluxe_profiles = nil', "server capability cache must include Deluxe profiles")
contains(store, 'deluxe_profile_restore = nil', "server capability cache must include Deluxe restore")
contains(store, 'deluxe_profile_sync = {}', "protected-profile backup must have independent sync state")
contains(store, 'function ServerStore:getDeluxeProfileState(server_id)', "protected-profile state reader missing")
contains(store, 'function ServerStore:saveDeluxeProfileState(server_id, state)', "protected-profile state writer missing")

contains(adapter, 'function DeluxeProfileAdapter.capture(store)', "Deluxe profile capture helper missing")
contains(adapter, 'function DeluxeProfileAdapter.apply(store, profile)', "Deluxe profile restore helper missing")
contains(adapter, 'server[access_field] = access_by_index[index]', "restored server must receive its original saved authentication")
contains(adapter, 'Deluxe-Sync profile authentication data is incomplete', "incomplete authentication must fail closed")
contains(adapter, 'server.data_sharing_version = existing and', "profile restore must preserve only local consent state")
contains(adapter, 'server.deluxe_config_backup_enabled = existing and existing.deluxe_config_backup_enabled == true or false', "newly restored servers must not inherit remote config-backup consent")

contains(main, 'DeluxeProfileAdapter = require("DeluxeProfileAdapter")', "Deluxe profile adapter must load with Deluxe-Sync")
contains(main, 'DeluxeProfileBackupSync = require("DeluxeProfileBackupSync")', "Deluxe profile backup implementation must load with Deluxe-Sync")
contains(main, 'function ProgressSyncDeluxe:serverSupportsDeluxeProfiles(server)', "Deluxe profile capability gate missing")
contains(main, 'function ProgressSyncDeluxe:serverSupportsDeluxeProfileRestore(server)', "Deluxe restore capability gate missing")
contains(main, 'function ProgressSyncDeluxe:cacheDeluxeProfileCapabilities(server, enhanced_capabilities)', "Deluxe capability cache helper missing")
contains(main, 'function ProgressSyncDeluxe:syncDeluxeProfileBackupForServer(server, callback)', "independent Deluxe-Sync config backup compatibility delegate missing")
contains(main, 'return self.deluxe_profile_backup_sync_service:sync(server, callback)', "Deluxe profile backup delegate must route to the extracted service")
contains(controller, 'steps[#steps + 1] = function(done) owner:syncDeluxeProfileBackupForServer(server, done) end', "controller must include consented Deluxe-Sync config backup")
contains(profile_backup_sync, 'server.deluxe_config_backup_enabled ~= true', "config backup must require explicit per-server consent")
contains(profile_backup_sync, 'local captured, capture_error = DeluxeProfileAdapter.capture(owner.store)', "consented config backup must capture the complete Deluxe setup")
contains(profile_backup_sync, 'client:putDeluxeProfile(server.username, server.userkey, payload', "protected config backup must use the dedicated Deluxe profile endpoint")
contains(profile_backup_sync, 'access = captured.access', "protected server authentication must accompany only the dedicated profile upload")
contains(profile_backup_sync, 'owner.store:getDeluxeProfileState(server.id)', "config backup dedupe must use independent state")
contains(profile_backup_sync, 'owner.store:saveDeluxeProfileState(server.id, {', "uploaded profile checksum must be persisted independently")
excludes(main, 'payload.deluxe_profile = {', "KOReader settings snapshots must never piggyback Deluxe-Sync credentials")
excludes(main, 'stored_state.deluxe_profile_checksum ==', "KOReader settings dedupe must not depend on protected-profile changes")

contains(main, 'function ProgressSyncDeluxe:checkDeluxeProfileCandidateForServer(server, client, callback)', "cross-device candidate compatibility delegate missing")
contains(main, 'self.restore_migration_controller:checkDeluxeProfileCandidateForServer(server, client, callback)', "candidate discovery must delegate to the restore controller")
contains(restore, 'client:getDeluxeProfileCandidate(server.username, server.userkey', "candidate discovery must use authenticated transport")
contains(main, 'function ProgressSyncDeluxe:showDeluxeProfileCandidatePrompt(server, candidate, client, registration)', "candidate confirmation compatibility delegate missing")
contains(restore, 'title = _("Deluxe-Sync backup found on another reader")', "candidate prompt must clearly identify a discovered backup, not a restore request")
contains(restore, 'text = _("Cancel")', "candidate migration must allow an explicit decline")
contains(restore, 'state.ignored_candidate_profile_id = profile_id', "declining a candidate must remember that exact backup")
contains(restore, 'text = _("Restore")', "candidate migration must use a direct Restore action")
excludes(restore, 'text = _("Prepare Restore")', "candidate migration must not expose an internal preparation step")
contains(restore, 'client:requestDeluxeProfileRestore(server.username, server.userkey', "reader must target the selected profile to itself")
contains(main, 'function ProgressSyncDeluxe:applyCurrentDeluxeProfileRestore(server, client, registration, expected_profile_id, callback)', "candidate Restore compatibility delegate missing")
contains(restore, 'self:applyCurrentDeluxeProfileRestore(server, client, registration, profile_id', "candidate Restore must proceed directly to validated application")
contains(restore, 'ignored_candidate_profile_id', "declined candidate state must be persisted")

contains(main, 'function ProgressSyncDeluxe:checkDeluxeProfileRestoreForServer(server, client, callback)', "pending Deluxe restore compatibility delegate missing")
contains(main, 'self.restore_migration_controller:checkDeluxeProfileRestoreForServer(server, client, callback)', "pending restore polling must delegate to the restore controller")
contains(restore, 'client:getCurrentDeluxeProfileRestore(server.username, server.userkey', "pending Deluxe restore must use authenticated transport")
contains(main, 'function ProgressSyncDeluxe:showDeluxeProfileRestorePrompt(server, restore, client, registration)', "Deluxe restore confirmation compatibility delegate missing")
contains(restore, 'text = _("Reject Restore Request")', "only a genuinely pending restore request should expose explicit rejection")
contains(restore, 'No new accounts are created.', "restore prompt must explain account identity preservation")
contains(restore, 'DeluxeProfileAdapter.apply(owner.store, {', "confirmed pending profile must be applied through the safe adapter")
contains(restore, 'client:completeDeluxeProfileRestore(server.username, server.userkey', "reader restore decision must be acknowledged")
contains(restore, 'This Deluxe-Sync restore request is no longer pending. No server setup was changed.', "stale restore prompt must fail closed")
contains(restore, 'UIManager:scheduleIn(0.5, function() owner:showDataSharingReview() end)', "restored servers must enter local data-sharing review")

contains(main, 'deluxe_profiles = true', "device registration must advertise Deluxe profile support")
contains(main, 'deluxe_profile_restore = true', "device registration must advertise Deluxe profile restore support")
contains(settings_sync, 'owner:checkDeluxeProfileMigrationForServer(server, client)', "normal Stage 9 lifecycle must check profile restore/candidates")
contains(main, 'function ProgressSyncDeluxe:refreshEnhancedCapabilitiesForAll()', "network capability refresh must remain the migration trigger")

local candidate_function = assert(restore:find('function RestoreMigrationController:showDeluxeProfileCandidatePrompt(server, candidate, client, registration)', 1, true))
local candidate_end = assert(restore:find('\nend\n\nfunction RestoreMigrationController:checkDeluxeProfileCandidateForServer', candidate_function, true))
local candidate_body = restore:sub(candidate_function, candidate_end)
local candidate_prompt = assert(candidate_body:find('title = _("Deluxe-Sync backup found on another reader")', 1, true))
local candidate_restore = assert(candidate_body:find('text = _("Restore")', candidate_prompt, true))
local request_restore = assert(candidate_body:find('client:requestDeluxeProfileRestore(server.username, server.userkey', candidate_restore, true))
local apply_restore = assert(candidate_body:find('self:applyCurrentDeluxeProfileRestore(server, client, registration, profile_id', request_restore, true))
assert(not candidate_body:find('Reject Restore Request', 1, true), "discovered backup candidates must not expose pending-request rejection")
assert(request_restore > candidate_restore, "restore request must only be created after explicit candidate confirmation")
assert(apply_restore > request_restore, "candidate Restore must immediately revalidate and apply the created request")

local restore_prompt = assert(restore:find('title = _("Restore Deluxe-Sync server setup?")', 1, true))
local restore_button = assert(restore:find('text = _("Restore")', restore_prompt, true))
local revalidate = assert(restore:find('client:getCurrentDeluxeProfileRestore(server.username, server.userkey', restore_button, true))
local apply_profile = assert(restore:find('DeluxeProfileAdapter.apply(owner.store, {', revalidate, true))
assert(revalidate > restore_button, "pending Deluxe profile must be revalidated after explicit restore confirmation")
assert(apply_profile > revalidate, "Deluxe profile must not be applied before pending-request revalidation")

print("deluxe_profile_sync_test.lua: OK")
