local function readFile(path)
    local file = assert(io.open(path, "rb"))
    local source = file:read("*a")
    file:close()
    return source
end

local main = readFile("main.lua")
local lifecycle = readFile("ProgressLifecycleController.lua")
local menu = readFile("PluginMenuController.lua")

local function contains(source, text)
    assert(source:find(text, 1, true), "missing expected dispatcher integration: " .. text)
end

contains(main, 'PluginMenuController = require("PluginMenuController")')
contains(main, 'function ProgressSyncDeluxe:onDispatcherRegisterActions()')
contains(main, 'return self.plugin_menu_controller:onDispatcherRegisterActions()')
contains(menu, 'local Dispatcher = require("dispatcher")')
contains(menu, 'Dispatcher:registerAction("deluxe_sync_set_autosync"')
contains(menu, 'Dispatcher:registerAction("deluxe_sync_toggle_autosync"')
contains(menu, 'Dispatcher:registerAction("deluxe_sync_push_progress"')
contains(menu, 'Dispatcher:registerAction("deluxe_sync_pull_progress"')
contains(menu, 'category="string", event="DeluxeSyncToggleAutoSync"')
contains(menu, 'args={true, false}')
contains(menu, 'event="DeluxeSyncPushProgress"')
contains(menu, 'event="DeluxeSyncPullProgress"')
contains(main, 'function ProgressSyncDeluxe:onDeluxeSyncToggleAutoSync(toggle)')
contains(main, 'return self.plugin_menu_controller:onDeluxeSyncToggleAutoSync(toggle)')
contains(main, 'function ProgressSyncDeluxe:onDeluxeSyncPushProgress()')
contains(main, 'return self.plugin_menu_controller:onDeluxeSyncPushProgress()')
contains(main, 'function ProgressSyncDeluxe:onDeluxeSyncPullProgress()')
contains(main, 'return self.plugin_menu_controller:onDeluxeSyncPullProgress()')
contains(menu, 'owner:pushAll(true)')
contains(menu, 'owner:pullAll(true)')
contains(menu, 'buttons_table = {{')
contains(menu, 'id = "top"')
contains(menu, 'id = "bottom"')
contains(menu, 'text = _("Close")')
assert(not menu:find('add_default_buttons = true', 1, true), "Credits must not inherit TextViewer's Find button")
contains(main, 'function ProgressSyncDeluxe:onReaderReady()')
contains(main, 'self.progress_lifecycle_controller:onReaderReady()')
contains(lifecycle, 'owner:onDispatcherRegisterActions()')

print("dispatcher_actions_test.lua: OK")
