local function readFile(path)
    local file = assert(io.open(path, "rb"))
    local source = file:read("*a")
    file:close()
    return source
end

local main = readFile("main.lua")
local servers = readFile("ServersPage.lua")
local settings = readFile("ServerSettingsPage.lua")
local browser = readFile("ServerLibraryBrowser.lua")
local style = readFile("DeluxeUIStyle.lua")
local menu = readFile("PluginMenuController.lua")

local function contains(source, text, message)
    assert(source:find(text, 1, true), message or ("missing expected integration: " .. text))
end

local function excludes(source, text, message)
    assert(not source:find(text, 1, true), message or ("unexpected legacy integration: " .. text))
end

contains(servers, 'local ServersPage = InputContainer:extend{', "server management must use a full-page InputContainer")
contains(servers, 'covers_fullscreen = true', "server management page must cover the full screen")
contains(servers, 'self.key_events = Dpad.pageKeyEvents(Device)', "server management must register the shared D-pad key map")
contains(servers, '_("Close")', "server chooser must expose Close")
contains(servers, '_("Synced Books")', "server chooser must expose direct Synced Books access")
contains(servers, '_("ENABLED SERVERS (%1)")', "server chooser must group enabled servers explicitly")
contains(servers, '_("DISABLED SERVERS (%1)")', "server chooser must group disabled servers explicitly")
contains(servers, '_("NOTE: Click to Enable/Disable or Click and HOLD to EDIT Server")', "server chooser must explain tap/hold behavior")
excludes(servers, 'Search servers', "server chooser should not expose search for the small configured-server list")
contains(servers, 'self.plugin_version and T(_("Deluxe-Sync v%1"), self.plugin_version)', "server chooser title must include the current plugin version")
contains(servers, 'local body = LeftContainer:new{', "server buttons must left-align the status circle and server name")
contains(servers, '_("+  Add server…")', "restored server chooser must retain Add Server")
contains(servers, 'function ServersPage:onDpadPress()', "server list must support center-button activation")
contains(servers, 'if self.key_header_index == 1 then self:openSyncedBooks() else self:closePage() end', "D-pad header activation must match the visible Synced Books / Close button order")
contains(servers, 'function ServersPage:onDpadMenu()', "D-pad Menu must open server details")
contains(servers, 'function ServersPage:onDpadPrevPage()', "server list must support hardware page-back keys")
contains(servers, 'function ServersPage:onDpadNextPage()', "server list must support hardware page-forward keys")
contains(servers, 'dimen = Geom:new{ w = width, h = height }', "server chooser section bars must have a full-width layout child")
contains(servers, 'DiagnosticLog.log("ui open", "Servers page", "servers", #self.servers)', "opening the Servers page must be logged")

contains(settings, 'local ServerSettingsPage = InputContainer:extend{', "server settings must use a full-page InputContainer")
contains(settings, 'covers_fullscreen = true', "server settings must cover the full screen")
contains(settings, 'self.key_events = Dpad.pageKeyEvents(Device)', "server settings must register the shared D-pad key map")
contains(settings, '_("ACCOUNT & CONNECTION")', "account and connection section missing")
contains(settings, '_("SYNC")', "sync section missing")
contains(settings, '_("DATA SHARED WITH THIS SERVER (IF SUPPORTED)")', "data-sharing section must clarify remote capability support")
contains(settings, '_("SERVER CAPABILITIES")', "server capability section missing")
contains(settings, '_("ACTIONS")', "server action section missing")
contains(settings, 'label = _("Server name")', "server-name editor missing")
contains(settings, 'label = _("URL")', "compact URL editor missing")
contains(settings, 'ellipsize(self.draft.url, 30)', "URL display must truncate long server addresses")
contains(settings, 'local label_natural_width = math.min(available, label_widget:getSize().w)', "settings layout must reserve the full label width before sizing long values")
contains(settings, 'local value_max_width = math.max(1, available - label_natural_width - value_gap)', "long values must shrink before their labels are clipped")
contains(settings, 'label = _("Username")', "username editor missing")
contains(settings, 'label = _("Password")', "masked password editor missing")
contains(settings, '_("••••••••")', "saved password must be masked in the overview")
contains(settings, 'label = _("Reading Progress"), value = _("ON (Default)")', "server Add/Edit page must show Reading Progress as ON (Default)")
contains(settings, 'label = _("Book Metadata")', "metadata-sharing toggle missing")
contains(settings, 'label = _("Annotations")', "compact annotations-sharing toggle missing")
excludes(settings, 'Annotations / Highlights / Notes', "server overview should use the compact Annotations label")
contains(settings, 'label = _("Vocabulary Builder")', "Vocabulary Builder rows missing")
contains(settings, 'label = _("Vocabulary Reading Context")', "Vocabulary reading-context consent row missing")
contains(settings, 'label = self.is_new and _("Save server first") or _("Authenticate / Sign in"), value = "", centered = true', "authentication action must be a centered standalone sign-in button")
contains(settings, 'local save_text = self.is_new and _("Save") or (self.dirty and _("Save *") or _("Close"))', "new-server header action must clearly say Save before authentication is available")
contains(settings, '{ label = _("Save"), value = "", callback = function()', "new-server actions must expose an explicit Save button")
excludes(settings, '_("Save / sign in")', "new-server UI must not imply that saving also authenticates")
contains(settings, '_("Saving server…")', "Save actions must give immediate transient activity feedback")
contains(settings, '_("Signing in and checking server capabilities…")', "authentication must immediately explain that capability checks are running")
contains(settings, 'self:requestAuthenticate()', "Authenticate / Sign in must route through the activity-feedback helper")
contains(settings, 'if cell.centered then', "server settings cells must support centered action rendering")
excludes(settings, 'label = _("Browse Synced Books")', "server edit page must not duplicate Synced Books access")
excludes(settings, '_("Disable Server")', "server edit page must not duplicate the enabled/disabled control")
contains(settings, 'label = _("Delete Server")', "delete-server action missing")
contains(settings, '_("Feature not supported by remote server")', "unsupported remote actions must explain why they cannot run")
contains(settings, 'if caps.account_recovery == false then', "Account Recovery must be gated by the remote capability")
contains(settings, 'self.dirty and _("Save *") or _("Close")', "clean server settings must expose Close instead of a redundant Save/OK action")
contains(settings, 'if not self.is_new and not self.dirty then', "clean Close action must leave the server settings page without saving")
contains(settings, 'function ServerSettingsPage:moveBody(direction)', "settings page must implement explicit row/column focus movement")
contains(settings, 'self.focus_rows[focus_row] = {', "settings page must build a two-column D-pad focus matrix")
contains(settings, 'fields = {{', "field editing must use a single-purpose one-field editor")
contains(settings, 'if field == "vocabulary_context_enabled" and self.draft.vocabulary_enabled ~= true then', "reading context must remain dependent on Vocabulary Builder")
contains(settings, 'local Style = require("DeluxeUIStyle")', "server settings must use the shared Deluxe-Sync UI scale")
contains(settings, 'local cell_height = Style.cellHeight()', "server settings must use the compact global cell height")
contains(settings, 'dimen = Geom:new{ w = width, h = height }', "server settings section bars must have a full-width layout child")
contains(settings, 'CenterContainer:new{', "server settings section labels should be centered")
contains(settings, 'if value ~= "" then label_text = label_text .. ":" end', "settings labels and values should render as one-line label/value pairs")
contains(settings, 'face = Font:getFace(value_face, Style.value_font)', "settings values must use the dedicated smaller value font")
contains(settings, 'local RightContainer = require("ui/widget/container/rightcontainer")', "settings values should remain right-aligned")
contains(settings, 'local value_right_inset = Style.scale(6)', "settings values should keep a small visual inset from the right border")
contains(settings, 'value_width = math.min(value_max_width, value_widget:getSize().w)', "settings values should claim only the width available after preserving the label")
contains(settings, 'local label_width = math.max(label_natural_width, available - value_width - value_gap)', "settings labels should keep their natural width while receiving any remaining space")
contains(settings, 'if value == true then return _("Supported") end', "capability rows should use compact Supported text")
contains(settings, 'and _("Registered") or capabilityText(caps.device_registration)', "device identity should use compact Registered text")
contains(settings, 'Style.sectionGap()', "server settings must use the compact shared section gap")
contains(style, 'value_font = 14', "settings values should use the final smaller shared value size")
contains(style, 'setting_label_font = 13', "all setting labels should use one shared title size")
contains(settings, 'local value_face = "smallinfofontbold"', "all setting values, including static capabilities, must use the same bold face")
contains(style, 'return math.max(36, Style.scale(38))', "one-line settings cells should use the denser shared height")
contains(style, 'return math.max(20, Style.scale(22))', "shared section bars should use the compact global height")
contains(style, 'return Style.scale(3)', "shared cell padding should stay condensed")
contains(settings, 'function ServerSettingsPage:applySavedServer(server)', "settings page must support in-place save/capability refresh")
contains(settings, 'DiagnosticLog.log("ui open", "Server settings page", "server", self.server.name or self.server.url or "new", "new", self.is_new)', "opening Server settings must be logged")
contains(browser, 'DiagnosticLog.log("ui open", "Server library page", "server", self.server_label, "entries", #self.entries)', "opening Synced Books must be logged")
contains(menu, 'diagnostic_log.log("ui open", "Deluxe-Sync menu")', "opening the Deluxe-Sync menu must be logged")

contains(main, 'local ServersPage = require("ServersPage")', "showServers must launch the full-page server browser")
contains(main, 'plugin_version = PLUGIN_VERSION,', "server chooser must receive the authoritative plugin version")
contains(menu, 'sub_item_table_func = function() return nil end,', "Configured Servers must display KOReader's submenu arrow while still opening the full-page server screen")
contains(menu, 'callback = function() owner:showServers() end,', "Configured Servers arrow item must retain the full-page callback")
contains(main, 'local ServerSettingsPage = require("ServerSettingsPage")', "server details must launch the full-page settings page")
contains(main, 'function ProgressSyncDeluxe:serverFromSettingsDraft', "full-page settings must preserve centralized server validation")
contains(main, 'function ProgressSyncDeluxe:showServerSettingsPage(existing)', "full-page server settings wrapper missing")
contains(main, 'function ProgressSyncDeluxe:addServerDialog(existing)', "legacy add-server callsites must remain compatible")
contains(main, 'self:showServerSettingsPage(existing or {})', "add-server compatibility wrapper must route to the new page")
contains(main, 'function ProgressSyncDeluxe:showServer(server)', "legacy server-detail callsites must remain compatible")
contains(main, 'self:showServerSettingsPage(server)', "server-detail compatibility wrapper must route to the new page")
contains(main, 'current:applySavedServer(saved)', "saving an existing server must stay on the settings page")
contains(main, 'show_result = false', "authentication capability refresh must not stack the legacy result dialog")
contains(main, '_("Server saved. Signing in and checking capabilities…")', "successful Save must explain that automatic authentication and capability refresh are starting")
local save_callback_start = assert(main:find('on_save = function(current, draft, password)', 1, true))
local signup_callback_start = assert(main:find('on_signup = function(current, draft, password)', save_callback_start, true))
local save_callback = main:sub(save_callback_start, signup_callback_start - 1)
assert(save_callback:find('self:testServer(saved, {', 1, true), "every Save must automatically authenticate and refresh server capabilities")
contains(main, '_("Server saved. Signed in and capabilities refreshed.")', "automatic post-save authentication must clearly report completion")
contains(main, 'on_authenticate = function(current, draft, password)', "server edit page must expose draft-aware authentication")
contains(main, 'local candidate = self:serverFromSettingsDraft(draft, password, false)', "authentication must use the current unsaved draft and replacement password")
contains(main, 'DiagnosticLog.log("ui action", "Authenticate / Sign in", "server", serverLabel(candidate))', "Authenticate / Sign in button presses must be logged")
contains(main, 'on_authorized = function(authenticated)', "draft settings must not be persisted until authentication succeeds")
contains(main, 'local saved = self.store:upsertServer(authenticated)', "successful authentication must save the validated draft")
contains(main, 'local authorized_server = options.on_authorized(server)', "capability probing must continue from the authenticated server after the save hook")
contains(main, '_("Signed in. Settings saved and capabilities refreshed.")', "successful authentication must clearly report sign-in, save, and capability refresh")
contains(main, 'local ConfirmBox = require("ui/widget/confirmbox")', "server deletion must use KOReader's native destructive confirmation")
contains(main, 'on_recovery = function(_current, draft)', "server recovery callback must not shadow KOReader's translation function")
contains(main, 'on_delete = function(_current, draft)', "server deletion callback must not shadow KOReader's translation function")
excludes(main, 'on_delete = function(_, draft)', "server deletion callback must never shadow KOReader's translation function before translated confirmation text")
contains(main, 'text = T(_("Delete %1 from Deluxe-Sync?\\nThis cannot be undone."), serverLabel(draft))', "server deletion confirmation must name the server and explain permanence")
contains(main, 'ok_text = _("Delete")', "server deletion confirmation must require an explicit Delete action")
contains(main, 'on_toggle = function(current, server, enabled)', "server chooser enable changes must persist immediately now that OK is replaced")
contains(main, 'on_browse = function(current)', "server chooser must launch Synced Books directly")
contains(main, 'capabilities.document_listing == true', "direct Synced Books launch must choose a library-capable enabled server")
excludes(main, 'self.servers_dialog = ButtonDialog:new', "legacy modal server list must be removed")
excludes(main, 'self.server_dialog = ButtonDialog:new', "legacy modal server details must be removed")

print("server_management_ui_test.lua: OK")
