local function readFile(path)
    local file = assert(io.open(path, "rb"))
    local source = file:read("*a")
    file:close()
    return source
end

local main = readFile("main.lua")
local browser = readFile("ServerLibraryBrowser.lua")
local controller = readFile("ServerLibraryController.lua")
local inspection = readFile("ServerRecordInspection.lua")
local cache = readFile("CoverCache.lua")
local placeholder = readFile("DeluxeCoverPlaceholder.lua")
local local_library = readFile("LocalLibrary.lua")
local store = readFile("ServerStore.lua")

local function contains(source, text, message)
    assert(source:find(text, 1, true), message or ("missing expected browser integration: " .. text))
end

local function excludes(source, text, message)
    assert(not source:find(text, 1, true), message or ("unexpected legacy browser integration: " .. text))
end

contains(browser, 'local ServerLibraryBrowser = InputContainer:extend{', "server library must be a full-page input container")
contains(browser, 'covers_fullscreen = true', "server library must cover the full screen")
contains(browser, 'local SWAP_ICON = ICONS .. "swap.svg"', "server browser must reuse the copied Libby server-cycle icon")
contains(browser, 'local REFRESH_ICON = ICONS .. "refresh.svg"', "server browser must reuse the copied Libby refresh icon")
contains(browser, 'local GRID_ICON = ICONS .. "view-grid.svg"', "server browser must reuse the copied Libby grid icon")
contains(browser, 'local LIST_ICON = ICONS .. "view-list.svg"', "server browser must reuse the copied Libby list icon")
contains(browser, 'local CLOSE_ICON = ICONS .. "close.svg"', "server browser must reuse the copied Libby close icon")
contains(browser, 'local LINK_ICON = ICONS .. "link.svg"', "server browser must use the dedicated link icon")
contains(browser, 'local SETTINGS_ICON = ICONS .. "settings.svg"', "server browser must expose the copied Libby settings icon")
contains(browser, 'function ServerLibraryBrowser:toggleLinkModeFromHeader()', "Link toolbar action must have an explicit activation path")
contains(browser, '_("This server does not support book linking.")', "unsupported Link taps must explain why linking is unavailable")
contains(browser, 'function() self:toggleLinkModeFromHeader() end, self:isHeaderFocused(4), self.link_mode, not self.loading', "Link toolbar taps must reach the activation path even when the current server cannot link")
contains(browser, 'function ServerLibraryBrowser:gridWidget(width, height)', "cover-grid mode missing")
contains(browser, 'local cols = self.grid_columns', "grid mode must use the persisted column count")
contains(browser, 'function ServerLibraryBrowser:listWidget(width, height)', "list mode missing")
contains(browser, 'self.grid_columns = math.max(2, math.min(8, tonumber(self.grid_columns) or 4))', "grid columns must be configurable with the Libby range")
contains(browser, 'self.grid_rows = math.max(1, math.min(6, tonumber(self.grid_rows) or 2))', "grid rows must be configurable while preserving the Deluxe 4x2 default")
contains(browser, 'self.list_rows = math.max(4, math.min(12, tonumber(self.list_rows) or 6))', "list rows must be configurable")
contains(browser, 'return math.max(1, self.grid_columns * self.grid_rows)', "grid page size must follow the configured layout")
contains(browser, '_("BOOKS WITH METADATA (%1)")', "metadata grouping heading missing")
contains(browser, '_("METADATA UNAVAILABLE (%1)")', "metadata-unavailable grouping heading missing")
contains(browser, 'dimen = Geom:new{ w = width, h = height }', "book-browser section bars must have a full-width layout child")
contains(browser, 'local group_h = Style.sectionHeight()', "book-browser group headers must use the shared compact section height")
contains(browser, 'local DeluxeCoverPlaceholder = require("DeluxeCoverPlaceholder")', "server browser must use the shared no-cover renderer")
contains(browser, 'return DeluxeCoverPlaceholder.new(width, height, {', "books without downloaded covers must render the shared fixed placeholder")
contains(browser, 'function ServerLibraryBrowser:localCover(entry)', "server browser must resolve a cover from a local matched KOReader book")
contains(browser, 'local server_cover = cachedServerCover(self.server, entry, width, height, focused, selected, disabled)', "downloaded server covers must remain the first cover source")
contains(browser, 'local local_cover = self:localCover(entry)', "local matched-book covers must be the fallback after the server cover cache")
contains(browser, 'RenderImage:scaleBlitBuffer(image, image_w, image_h, disposable == true)', "resizing a reusable local cover must never free the cached source BlitBuffer")
contains(browser, 'return framedCover(local_cover, width, height, focused, selected, disabled, false), true', "local matched-book covers must remain caller-owned across list/grid rebuilds")
contains(browser, 'function ServerLibraryBrowser:releaseLocalCovers(entries)', "caller-owned cached local covers must have an explicit release path")
contains(browser, 'function ServerLibraryBrowser:releaseAllLocalCovers()', "session shelf caches must release every retained local cover on browser close")
contains(browser, 'if not switching_servers then self:releaseLocalCovers(previous_entries) end', "explicit same-server refresh must release invalidated local covers after the loading widget replaces them")
contains(controller, 'if target.releaseAllLocalCovers then target:releaseAllLocalCovers()', "closing the browser must release local covers retained by every prepared server shelf")
contains(browser, 'local function gridTitle(entry)', "grid cards must normalize their one-line display title independently from list identity text")
contains(browser, 'if title == nil or tostring(title) == "" then return _("Unknown") end', "grid books without a real title must display only Unknown")
contains(browser, 'local title_h = Style.scale(18)', "every grid card must reserve the same fixed title row")
contains(browser, 'local status_h = Style.scale(20)', "every grid card must reserve the same fixed progress row")
contains(browser, 'local item_gap = Style.scale(2)', "cover/title/progress rows must retain a minimal fixed gap")
contains(browser, 'text = safeText(gridTitle(entry), 32)', "grid titles must use the single-line TextWidget path")
contains(placeholder, 'dependencies/icons/no-cover.png', "shared no-cover renderer must use the bundled no-cover image")
contains(main, 'DeluxeCoverPlaceholder = require("DeluxeCoverPlaceholder")', "legacy detail/preview screens must load the shared no-cover renderer")
excludes(main, 'Cover unavailable', "all legacy cover placeholders must use the shared image instead of text/icon fallbacks")
excludes(browser, 'invert = selected == true', "header link mode must not draw the old boxed/inverted icon treatment")
contains(browser, 'local underline = FrameContainer:new{', "browser header must render one continuous underline")
contains(browser, 'local status_face = Font:getFace("cfont", 15)', "list status column must match the Libby list typography")
contains(browser, 'T(_("Linked · %1 versions"), tonumber(entry.version_count) or 0)', "logical books must retain linked version information in list metadata")
contains(browser, 'T(_("Progress: %1"), string.format("%d%%", math.floor(value + 0.5)))', "grid/list status must explicitly label reading progress")
contains(browser, '_("Progress: —")', "unknown reading progress must remain explicitly labeled")
excludes(browser, 'Metadata available', "title/author alone must never be described as metadata availability")
excludes(browser, 'Filename / document identity', "raw records should not spend a list row on a misleading metadata note")
contains(browser, 'self.view_mode = self.view_mode == "grid" and "list" or "grid"', "grid/list toggle missing")
contains(browser, 'if self.on_view_mode_change then self.on_view_mode_change(self.view_mode) end', "grid/list preference must be persistable")
contains(browser, 'function ServerLibraryBrowser:showLayoutSettings()', "synced books must expose layout settings")
contains(browser, 'function ServerLibraryBrowser:setLayout(columns, rows, list_rows)', "layout settings must update the live browser")
contains(browser, 'icon = "chevron.first"', "touch pagination must expose a first-page action")
contains(browser, 'icon = "chevron.left"', "touch pagination must expose a previous-page action")
contains(browser, 'icon = "chevron.right"', "touch pagination must expose a next-page action")
contains(browser, 'icon = "chevron.last"', "touch pagination must expose a last-page action")
contains(browser, 'function ServerLibraryBrowser:onBrowserSwipeNext()', "touch swipe-next paging missing")
contains(browser, 'function ServerLibraryBrowser:onBrowserSwipePrev()', "touch swipe-previous paging missing")
contains(browser, 'self.cover_fetch_scheduled = false', "cover prefetch scheduling must be explicitly tracked")
contains(browser, 'function ServerLibraryBrowser:pendingVisibleCover()', "cover prefetch must check for actual pending visible covers")
contains(browser, 'if self.cover_fetch_active or self.cover_fetch_scheduled then return false end', "cover prefetch must coalesce active/scheduled work")
contains(browser, 'if not self:pendingVisibleCover() then return false end', "idle shelves must not schedule no-op cover ticks")
contains(browser, 'local ok, downloaded_path = pcall(CoverCache.download, self.server, entry.item)', "cover completion must distinguish successful downloads from failures")
contains(browser, 'if ok and downloaded_path then', "only successful cover downloads should rebuild the shelf")
excludes(browser, 'UIManager:nextTick(function() self:prefetchVisibleCover() end)', "browser rebuilds must not unconditionally schedule no-op cover ticks")
contains(browser, 'if self.closed or self.loading or self.link_mode or #self.servers < 2 then return end', "server cycling must lock while loading/linking")
contains(browser, 'if self.closed or self.loading or self.link_mode then return end', "refresh must lock while loading/linking")
contains(browser, 'function ServerLibraryBrowser:onDpadPress()', "D-pad center-button support missing")
contains(browser, 'function ServerLibraryBrowser:onDpadPrevPage()', "hardware previous-page support missing")
contains(browser, 'function ServerLibraryBrowser:onDpadNextPage()', "hardware next-page support missing")
contains(browser, 'function ServerLibraryBrowser:setLoading(server, server_label)', "browser must expose an in-place loading state for explicit refreshes")
contains(browser, 'function ServerLibraryBrowser:replaceLibrary(state, restoring_prepared)', "browser must replace or restore prepared server shelves in place")
contains(browser, 'function ServerLibraryBrowser:rememberCurrentShelf()', "browser must retain prepared per-server shelf state for the current session")
contains(browser, 'function ServerLibraryBrowser:restorePreparedShelf(server_id)', "browser must restore a prepared server shelf without rebuilding local matches")
contains(browser, 'cover_attempted = self.cover_attempted', "prepared shelves must retain cover-attempt state instead of repeating failed cover work")
contains(browser, 'self.cover_attempted = state.cover_attempted or {}', "restoring a prepared shelf must restore its cover-attempt state")
contains(browser, 'if self.loading and self.key_header_index ~= 6 then return true end', "D-pad must not trigger disabled header actions during a library fetch")
contains(main, 'function ProgressSyncDeluxe:showCachedServerLibrary(server, browser)', "Synced Books must expose a cache-first browser entry point")
contains(controller, 'browser.restorePreparedShelf and browser:restorePreparedShelf(server.id)', "server switching must prefer the fully prepared in-session shelf before rebuilding persistent cache data")
contains(main, 'function ProgressSyncDeluxe:refreshServerLibrary(server, browser)', "explicit library refresh compatibility delegate missing")
contains(controller, 'browser:setLoading(server, self.deps.server_label(server))', "explicit refresh must invalidate the active prepared shelf and keep the browser visible while loading")
contains(controller, 'self:showServerLibrary(server, documents, authoritative, logical_mode, browser, refreshed_at)', "library responses must reuse the existing browser and preserve refresh time")
contains(controller, 'self:showCachedServerLibrary(servers[next_index], browser)', "server cycling must prefer the next server cache before any network request")
contains(main, 'self:showCachedServerLibrary(target)', "top-level Browse Synced Books must prefer cached documents")
excludes(main, 'self:showCachedServerLibrary(saved)', "server settings must not retain a duplicate per-server Browse Synced Books action")
contains(controller, 'owner.store:setKnownDocuments(server.id, data.documents, { logical_mode = false, refreshed_at = refreshed_at })', "successful raw refreshes must timestamp the cache")
contains(controller, 'owner.store:setKnownDocuments(server.id, data.books, { logical_mode = true, refreshed_at = refreshed_at })', "successful logical refreshes must timestamp the cache")
contains(store, 'known_documents_meta = {}', "document cache metadata must have independent local persistence")
contains(store, 'function ServerStore:getKnownDocumentsMeta(server_id)', "document cache refresh metadata reader missing")
contains(browser, 'updatedText(self.refreshed_at)', "browser header must expose the cached shelf refresh time")
local test_server_start = assert(main:find('function ProgressSyncDeluxe:testServer(server, options)', 1, true))
local show_server_start = assert(main:find('function ProgressSyncDeluxe:showServer(server)', test_server_start, true))
local test_server_body = main:sub(test_server_start, show_server_start - 1)
excludes(test_server_body, 'self.store:setKnownDocuments(server.id, data.documents)', "capability probes must not overwrite the authoritative shelf cache with raw documents")
local refresh_start = assert(controller:find('function ServerLibraryController:refreshServerLibrary(server, browser)', 1, true))
local link_picker_start = assert(controller:find('function ServerLibraryController:showLogicalLinkPicker(server, documents)', refresh_start, true))
local refresh_body = controller:sub(refresh_start, link_picker_start - 1)
excludes(refresh_body, 'server.capabilities and server.capabilities.document_listing == false', "the explicit Refresh action must retry the server even after a prior listing failure")
contains(refresh_body, 'local listing_unsupported = status == 404 or status == 405', "temporary refresh failures must preserve cached-library browse capability")
contains(refresh_body, 'if listing_unsupported then owner.store:setCapability(server.id, "document_listing", false) end', "only definitively unsupported listing responses may disable Synced Books")
excludes(controller, 'self:refreshServerLibrary(browse_servers[next_index])', "server cycling must never use the old close-and-reopen path")
excludes(browser, 'local _, _, pages = self:visibleBounds()', "footer pagination must never shadow the translation function named _")
excludes(browser, 'for _ =', "server library browser must never shadow the translation function with numeric discard loops")
contains(browser, 'if self.link_mode then self:setLinkMode(false); return end', "Back/close must leave link mode before leaving the browser")

contains(cache, 'DataStorage:getSettingsDir() .. "/deluxe-sync/covers"', "cover cache must live under KOReader settings")
contains(cache, 'if cover_url:sub(1, 1) == "/" then return base .. cover_url end', "relative cover URLs must resolve only against the configured sync server")
contains(cache, 'if cover_url:sub(1, #base + 1) == base .. "/" then return cover_url end', "absolute cover URLs must be limited to the configured sync server")
contains(cache, 'return nil', "untrusted external cover URLs must be rejected")

contains(store, 'function ServerStore:getSetting(key, default)', "persistent browser-view setting getter missing")
contains(store, 'function ServerStore:setSetting(key, value)', "persistent browser-view setting setter missing")
contains(main, 'ServerLibraryController = require("ServerLibraryController")', "main must load the extracted server-library controller")
contains(main, 'return self.server_library_controller:showServerLibrary(server, documents, authoritative, logical_mode, existing_page, refreshed_at)', "main server-library compatibility delegate missing")
contains(controller, 'local ServerLibraryBrowser = require("ServerLibraryBrowser")', "server-library controller must launch the full-page browser")
contains(controller, 'on_local_cover = function(unused_browser, entry)', "server-library controller must provide the browser with a local-cover resolver without shadowing translation")
contains(controller, 'return owner.ui.bookinfo:getCoverImage(owner.ui.document, match.path)', "browser local covers must use the same KOReader bookinfo cover source as Server Record inspection")
contains(controller, 'view_mode = owner.store:getSetting("server_library_view_mode", "grid")', "controller must restore grid/list preference")
contains(controller, 'owner.store:setSetting("server_library_view_mode", mode)', "controller must persist grid/list preference")
contains(controller, 'grid_columns = owner.store:getSetting("server_library_grid_columns", 4)', "controller must restore grid column preference")
contains(controller, 'grid_rows = owner.store:getSetting("server_library_grid_rows", 2)', "controller must restore grid row preference")
contains(controller, 'list_rows = owner.store:getSetting("server_library_list_rows", 6)', "controller must restore list row preference")
contains(controller, 'owner.store:setSetting("server_library_grid_columns", columns)', "controller must persist grid columns")
contains(controller, 'owner.store:setSetting("server_library_grid_rows", rows)', "controller must persist grid rows")
contains(controller, 'owner.store:setSetting("server_library_list_rows", list_rows)', "controller must persist list rows")
contains(controller, 'percentage = tonumber(item.percentage)', "browser entries must carry server reading progress")
contains(controller, 'grid_title = known_title or _("Unknown")', "grid identity must never fall back to filenames or checksum fragments when a title is unknown")
contains(controller, 'local function remoteMetadataAvailable(item)', "metadata grouping must explicitly classify remote KOSync metadata")
contains(controller, 'if item.metadata_available == true then return true end', "server-declared metadata availability must be honored")
contains(controller, 'metadataValuePresent(item.title) or metadataValuePresent(item.authors)', "remote title or author must classify the record as metadata-available")
contains(controller, 'local has_metadata = remoteMetadataAvailable(item)', "cover availability and local matches must not control metadata grouping")
contains(controller, 'caps.logical_books == true and caps.logical_library == true', "link mode must remain capability-gated")
contains(controller, 'self:showLogicalProgressSourcePicker(active_server, selected)', "link mode must reuse logical progress-source selection for the displayed server")
contains(controller, 'self:showLogicalBookInspection(active_server, entry.item, browser)', "logical entries must overlay inspection on the displayed browser")
contains(controller, 'owner:showServerDocumentInspection(active_server, entry.item, entry.match, active_documents, active_authoritative, active_logical_mode, browser, entry)', "raw entries must overlay inspection on the displayed browser state")
local open_handler = assert(controller:find('on_open_entry = function(browser, entry)', 1, true))
local link_handler = assert(controller:find('on_link_selected = function(browser, selected_entries)', open_handler, true))
local open_body = controller:sub(open_handler, link_handler - 1)
excludes(open_body, 'closeBrowser(browser)', "opening Server Record must not destroy the cached shelf")
excludes(controller, 'for _, item in ipairs(documents) do', "library entry normalization must never reuse the translation symbol as a loop variable")
excludes(browser, 'for _,', "server library browser must never shadow the translation function with discard loop variables")
excludes(main, 'self.library_dialog = ButtonDialog:new', "old tracked-books ButtonDialog must be removed")

contains(local_library, 'function LocalLibrary.findByDocument(document, root)', "server-record Find Match must have a sidecar lookup helper")
contains(local_library, 'LuaSettings:open(sidecar_path)', "Find Match must inspect KOReader sidecar settings instead of hashing every local book")
contains(local_library, 'settings:readSetting("partial_md5_checksum")', "Find Match must compare KOReader's stored partial MD5")
contains(local_library, 'settings:readSetting("doc_path")', "Find Match must recover the local book path from the sidecar")
contains(local_library, 'settings:readSetting("doc_props")', "Find Match must recover local title/author metadata")
contains(main, 'local ServerRecordInspection = require("ServerRecordInspection")', "main must retain a thin Server Record compatibility delegate")
contains(main, 'return ServerRecordInspection.show(self, server, doc, match, documents, authoritative, logical_mode, {', "Server Record rendering must be delegated to the extracted module")
contains(inspection, 'text = _("Find Match")', "unmatched server records must expose a Find Match action")
contains(inspection, 'local found = LocalLibrary.findByDocument(doc.document)', "Find Match must search by the full remote document identity")
contains(inspection, 'if not browser or browser.closed then', "Server Record Back must reveal a live cached browser without rebuilding the shelf")
contains(inspection, 'browser_entry.match = found', "Find Match must update the existing cached browser entry in place")
contains(inspection, 'if browser and not browser.closed then browser:updateItems() end', "Find Match must redraw the existing cached shelf instead of rescanning it")
contains(inspection, 'plugin:showServerDocumentInspection(server, doc, found, documents, authoritative, logical_mode, browser, browser_entry)', "successful Find Match must preserve the existing browser through the compatibility delegate")
contains(controller, 'if not browser or browser.closed then self:showCachedServerLibrary(server) end', "linked-book Back must reveal a live browser or fall back to cache without an implicit refresh")
contains(main, 'function ProgressSyncDeluxe:confirmUnlinkLogicalBook(server, logical_book, browser)', "unlink flow must know which cached browser it invalidates")
contains(inspection, 'text = compactText(match.path, 34)', "server-record local paths must be visually bounded instead of rendering absolute paths verbatim")
contains(inspection, 'local remote_label_face = Font:getFace("smallinfofont", Style.setting_label_font)', "server-record labels must use the shared Deluxe-Sync typography")
contains(inspection, 'local remote_value_face = Font:getFace("smallinfofontbold", Style.value_font)', "server-record values must use the shared Deluxe-Sync typography")
contains(inspection, 'addRemoteRow(_("Document ID"), document_label)', "server-record document identity must use the compact visual label")

print("server_library_browser_test.lua: OK")
