local function readFile(path)
    local file = assert(io.open(path, "rb"))
    local source = file:read("*a")
    file:close()
    return source
end

local main = readFile("main.lua")
local store = readFile("ServerStore.lua")
local client = readFile("SyncClient.lua")
local api = readFile("api.json")
local adapter = readFile("SettingsBackupAdapter.lua")

local function contains(source, text, message)
    assert(source:find(text, 1, true), message or ("missing settings-backup integration: " .. text))
end

contains(api, '"put_settings_backup"', "settings backup API method missing")
contains(api, '"path": "/api/v1/settings/backups"', "settings backup API path mismatch")
contains(api, '"client_redacted_count"', "client-side redaction count must be carried as metadata")
contains(api, '"get_current_settings_restore"', "pending restore API method missing")
contains(api, '"complete_settings_restore"', "restore acknowledgement API method missing")
contains(client, 'function SyncClient:putSettingsBackup(username, userkey, payload, callback)', "settings backup SyncClient helper missing")
contains(client, 'function SyncClient:getCurrentSettingsRestore(username, userkey, legacy_device_id, koreader_device_id, callback)', "pending restore SyncClient helper missing")
contains(client, 'function SyncClient:completeSettingsRestore(username, userkey, request_id, payload, callback)', "restore acknowledgement SyncClient helper missing")

contains(store, 'settings_backup_sync = {}', "per-server settings backup state missing")
contains(store, 'function ServerStore:getSettingsBackupState(server_id)', "settings backup state getter missing")
contains(store, 'function ServerStore:saveSettingsBackupState(server_id, state)', "settings backup state persistence missing")
contains(store, 'self.data.settings_backup_sync[id] = nil', "removing a server must clear settings backup state")
contains(store, 'settings_backups = nil', "server capability cache must include settings backups")
contains(store, 'settings_restore = nil', "server capability cache must include settings restore")

contains(adapter, 'local sensitive_key_parts = {', "client-side secret deny-list missing")
contains(adapter, 'device_id = true', "device identity must be excluded from snapshots")
contains(adapter, 'function SettingsBackupAdapter.capture()', "settings capture helper missing")
contains(adapter, 'function SettingsBackupAdapter.apply(settings)', "same-device settings restore helper missing")

contains(main, 'SettingsBackupAdapter = require("SettingsBackupAdapter")', "settings backup adapter must load with Deluxe-Sync")
contains(main, 'function ProgressSyncDeluxe:serverSupportsSettingsBackups(server)', "settings backup capability gate missing")
contains(main, 'function ProgressSyncDeluxe:serverSupportsSettingsRestore(server)', "settings restore capability gate missing")
contains(main, 'function ProgressSyncDeluxe:cacheSettingsBackupCapabilities(server, enhanced_capabilities)', "settings capability cache helper missing")
contains(main, 'function ProgressSyncDeluxe:syncSettingsBackupForServer(server, callback)', "per-server settings backup sync missing")
contains(main, 'function ProgressSyncDeluxe:syncSettingsBackupsForAll()', "multi-server settings backup trigger missing")
contains(main, 'SettingsBackupAdapter.capture()', "settings must be sanitized before upload")
contains(main, 'client_redacted_count = captured.redacted_count', "client redaction count must accompany sanitized payload")
contains(main, 'client:putSettingsBackup(server.username, server.userkey', "sanitized settings snapshot must upload")
contains(main, 'self.store:getSettingsBackupState(server.id)', "unchanged snapshot detection state missing")
contains(main, 'stored_state.checksum == captured.checksum', "unchanged snapshots must be skipped")
contains(main, 'function ProgressSyncDeluxe:checkSettingsRestoreForServer(server, client, callback)', "pending restore polling missing")
contains(main, 'client:getCurrentSettingsRestore(server.username, server.userkey', "restore polling must use authenticated transport")
contains(main, 'function ProgressSyncDeluxe:showSettingsRestorePrompt(server, restore, client, registration)', "reader confirmation prompt missing")
contains(main, 'text = _("Later")', "restore prompt must allow deferral")
contains(main, 'text = _("Restore")', "restore prompt must require explicit restore action")
contains(main, 'text = _("Reject Restore Request")', "restore prompt must allow explicit rejection")
contains(main, 'SettingsBackupAdapter.apply(snapshot.settings)', "settings must only apply after reader confirmation")
contains(main, 'client:completeSettingsRestore(server.username, server.userkey', "reader restore decision must be acknowledged")
contains(main, 'settings_backups = true', "device registration must advertise settings-backup support")
contains(main, '_("Settings Backups")', "server capability UI must expose settings backups")
contains(main, 'UIManager:scheduleIn(2.5, function() self:syncSettingsBackupsForAll() end)', "reader-ready settings backup trigger missing")
contains(main, 'function ProgressSyncDeluxe:refreshEnhancedCapabilities(server, client)', "silent enhanced capability refresh helper missing")
contains(main, 'function ProgressSyncDeluxe:refreshEnhancedCapabilitiesForAll()', "multi-server enhanced capability refresh missing")
contains(main, 'self:refreshEnhancedCapabilities(server, client)', "network refresh must update enhanced capabilities before follow-up sync")
contains(main, 'self:checkSettingsRestoreForServer(server, client)', "network refresh must poll pending settings restore requests")
contains(main, 'UIManager:scheduleIn(1, function() self:refreshEnhancedCapabilitiesForAll() end)', "network reconnect enhanced capability refresh trigger missing")
contains(main, 'self:syncSettingsBackupsForAll()', "normal lifecycle must trigger settings backup sync")

local prompt_position = assert(main:find('text = _("Restore")', 1, true))
local apply_position = assert(main:find('SettingsBackupAdapter.apply(snapshot.settings)', prompt_position, true))
assert(apply_position > prompt_position, "settings restore must not apply before explicit reader confirmation")

print("settings_backup_sync_test.lua: OK")
