local function readFile(path)
    local file = assert(io.open(path, "rb"))
    local source = file:read("*a")
    file:close()
    return source
end

local main = readFile("main.lua")
local store = readFile("ServerStore.lua")
local client = readFile("SyncClient.lua")
local api = readFile("api.json")
local adapter = readFile("SettingsBackupAdapter.lua")

local function contains(source, text, message)
    assert(source:find(text, 1, true), message or ("missing settings-backup integration: " .. text))
end

contains(api, '"put_settings_backup"', "settings backup API method missing")
contains(api, '"path": "/api/v1/settings/backups"', "settings backup API path mismatch")
contains(api, '"client_redacted_count"', "client-side redaction count must be carried as metadata")
contains(api, '"get_settings_backup"', "stored snapshot presence API method missing")
contains(api, '"path": "/api/v1/settings/backups/:snapshot_id"', "stored snapshot presence API path mismatch")
contains(api, '"get_current_settings_restore"', "pending restore API method missing")
contains(api, '"complete_settings_restore"', "restore acknowledgement API method missing")
contains(client, 'function SyncClient:putSettingsBackup(username, userkey, payload, callback)', "settings backup SyncClient helper missing")
contains(client, 'function SyncClient:getSettingsBackup(username, userkey, snapshot_id, callback)', "stored snapshot presence helper missing")
contains(client, 'function SyncClient:getCurrentSettingsRestore(username, userkey, legacy_device_id, koreader_device_id, callback)', "pending restore SyncClient helper missing")
contains(client, 'function SyncClient:completeSettingsRestore(username, userkey, request_id, payload, callback)', "restore acknowledgement SyncClient helper missing")

contains(store, 'settings_backup_sync = {}', "per-server settings backup state missing")
contains(store, 'function ServerStore:getSettingsBackupState(server_id)', "settings backup state getter missing")
contains(store, 'function ServerStore:saveSettingsBackupState(server_id, state)', "settings backup state persistence missing")
contains(store, 'self.data.settings_backup_sync[id] = nil', "removing a server must clear settings backup state")
contains(store, 'settings_backups = nil', "server capability cache must include settings backups")
contains(store, 'settings_restore = nil', "server capability cache must include settings restore")

contains(adapter, 'local sensitive_key_parts = {', "client-side secret deny-list missing")
contains(adapter, 'device_id = true', "device identity must be excluded from snapshots")
contains(adapter, 'local volatile_exact_keys = {', "KOReader runtime-state exclusion list missing")
contains(adapter, 'lastfile = true', "last-opened document must not churn settings snapshots")
contains(adapter, 'frontlight_intensity = true', "current frontlight state must not churn settings snapshots")
contains(adapter, 'CoreReaderSettings = require("CoreReaderSettings")', "core-only settings contract must load")
contains(adapter, 'SettingsBackupAdapter.SCHEMA_VERSION = 2', "core-only settings backups must advertise schema 2")
contains(adapter, 'unknown_root_key = path == "" and not CoreReaderSettings.allows(key)', "unknown plugin-owned root settings must fail closed")
contains(adapter, 'function SettingsBackupAdapter.capture()', "settings capture helper missing")
contains(adapter, 'function SettingsBackupAdapter.apply(settings)', "same-device settings restore helper missing")

contains(main, 'SettingsBackupAdapter = require("SettingsBackupAdapter")', "settings backup adapter must load with Deluxe-Sync")
contains(main, 'function ProgressSyncDeluxe:serverSupportsSettingsBackups(server)', "settings backup capability gate missing")
contains(main, 'function ProgressSyncDeluxe:serverSupportsSettingsRestore(server)', "settings restore capability gate missing")
contains(main, 'function ProgressSyncDeluxe:cacheSettingsBackupCapabilities(server, enhanced_capabilities)', "settings capability cache helper missing")
contains(main, 'function ProgressSyncDeluxe:syncSettingsBackupForServer(server, callback)', "per-server settings backup sync missing")
contains(main, 'server.settings_backup_enabled ~= true', "KOReader settings backup must require explicit per-server consent")
contains(main, 'function ProgressSyncDeluxe:syncSettingsBackupsForAll()', "multi-server settings backup trigger missing")
contains(main, 'SettingsBackupAdapter.capture()', "settings must be sanitized before upload")
contains(main, 'SettingsBackupLifecycle = require("SettingsBackupLifecycle")', "settings backup lifecycle state machine must load with Deluxe-Sync")
contains(main, 'client_redacted_count = captured.redacted_count', "client redaction count must accompany sanitized payload")
contains(main, 'local upload_client = self:newClient(server)', "snapshot replacement must use a fresh request client")
contains(main, 'upload_client:putSettingsBackup(server.username, server.userkey', "sanitized settings snapshot must upload")
contains(main, 'self.store:getSettingsBackupState(server.id)', "unchanged snapshot detection state missing")
contains(main, 'stored_state.checksum == captured.checksum', "unchanged snapshots must be detected")
contains(main, 'SettingsBackupLifecycle.run({', "settings backup convergence must use the executable lifecycle state machine")
contains(main, 'client:getSettingsBackup(server.username, server.userkey, snapshot_id', "unchanged snapshots must be revalidated against server state")
contains(main, 'self.store:saveSettingsBackupState(server.id, stored_state)', "server-deleted snapshots must invalidate remembered local snapshot ids")
contains(main, 'UIManager:scheduleIn(15, function()', "settings backup in-flight guard must have a watchdog")
contains(main, 'function ProgressSyncDeluxe:checkSettingsRestoreForServer(server, client, callback)', "pending restore polling missing")
contains(main, 'client:getCurrentSettingsRestore(server.username, server.userkey', "restore polling must use authenticated transport")
contains(main, 'function ProgressSyncDeluxe:showSettingsRestorePrompt(server, restore, client, registration)', "reader confirmation prompt missing")
contains(main, 'text = _("Later")', "restore prompt must allow deferral")
contains(main, 'text = _("Restore")', "restore prompt must require explicit restore action")
contains(main, 'text = _("Reject Restore Request")', "restore prompt must allow explicit rejection")
contains(main, 'SettingsBackupAdapter.apply(current_snapshot.settings)', "settings must only apply from a still-pending snapshot after reader confirmation")
contains(main, 'This restore request is no longer pending. No settings were changed.', "stale restore prompts must fail closed")
contains(main, 'client:completeSettingsRestore(server.username, server.userkey', "reader restore decision must be acknowledged")
contains(main, 'settings_backups = true', "device registration must advertise settings-backup support")
contains(main, '_("Settings Backups")', "server capability UI must expose settings backups")
contains(main, 'UIManager:scheduleIn(2, function() self:nudgeOptionalDataAll(false) end)', "reader-ready optional-data coordinator trigger missing")
contains(main, 'function ProgressSyncDeluxe:refreshEnhancedCapabilities(server, client)', "silent enhanced capability refresh helper missing")
contains(main, 'function ProgressSyncDeluxe:refreshEnhancedCapabilitiesForAll()', "multi-server enhanced capability refresh missing")
contains(main, 'self:refreshEnhancedCapabilities(server, client)', "network refresh must update enhanced capabilities before follow-up sync")
contains(main, 'self:checkSettingsRestoreForServer(server, client)', "network refresh must poll pending settings restore requests")
contains(main, 'UIManager:scheduleIn(1, function() self:refreshEnhancedCapabilitiesForAll() end)', "network reconnect enhanced capability refresh trigger missing")
contains(main, 'self:nudgeOptionalDataAll(false)', "normal lifecycle must nudge optional-data convergence")
contains(main, 'steps[#steps + 1] = function(done) self:syncSettingsBackupForServer(server, done) end', "coordinator must include consented settings-backup work")

local settings_sync = assert(main:find('function ProgressSyncDeluxe:syncSettingsBackupForServer(server, callback)', 1, true))
local consent_gate = assert(main:find('server.settings_backup_enabled ~= true', settings_sync, true))
local first_capture = assert(main:find('SettingsBackupAdapter.capture()', settings_sync, true))
assert(consent_gate < first_capture, "disabled KOReader settings backup must not inspect local settings")

local prompt_position = assert(main:find('text = _("Restore")', 1, true))
local revalidate_position = assert(main:find('client:getCurrentSettingsRestore(server.username, server.userkey', prompt_position, true))
local apply_position = assert(main:find('SettingsBackupAdapter.apply(current_snapshot.settings)', revalidate_position, true))
assert(revalidate_position > prompt_position, "restore request must be revalidated after explicit reader confirmation")
assert(apply_position > revalidate_position, "settings restore must not apply before pending-request revalidation")

print("settings_backup_sync_test.lua: OK")
